
package monaco_editor.monaco.editor;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import net.kurobako.monacofx.js.JsContext;
import net.kurobako.monacofx.js.JsProxy;
import netscape.javascript.JSObject;

/**
 * <p>A rich diff editor.</p>
 * See {@code monaco.d.ts:4566:32}<br>
 * Original signature:<br>
 * {@code export interface IDiffEditor extends IEditor  }<br>
 */
@SuppressWarnings("unused")
public class IDiffEditor extends IEditor {

	public IDiffEditor(@Nonnull JsContext context, @Nonnull Object receiver) { super(context, receiver); }

 
	public IDiffEditor(@Nonnull JsContext context) { super(context); }

 
	/**
	 * <p>Get information based on computed diff about a line number from the modified model.
	 * If the diff computation is not finished or the model is missing, will return null.</p>
	 * See {@code monaco.d.ts:4618:41}<br>
	 * Original signature:<br>
	 * {@code getDiffLineInformationForModified(lineNumber: number): IDiffLineInformation | null; }<br>
	 */
	public Optional<IDiffLineInformation> getDiffLineInformationForModified(@Nonnull Double lineNumber) { return Optional.ofNullable(call("getDiffLineInformationForModified", IDiffLineInformation::new, lineNumber)); }

 	/**
	 * <p>Get information based on computed diff about a line number from the original model.
	 * If the diff computation is not finished or the model is missing, will return null.</p>
	 * See {@code monaco.d.ts:4613:41}<br>
	 * Original signature:<br>
	 * {@code getDiffLineInformationForOriginal(lineNumber: number): IDiffLineInformation | null; }<br>
	 */
	public Optional<IDiffLineInformation> getDiffLineInformationForOriginal(@Nonnull Double lineNumber) { return Optional.ofNullable(call("getDiffLineInformationForOriginal", IDiffLineInformation::new, lineNumber)); }

 	/**
	 * See {@code monaco.d.ts:4570:18}<br>
	 * Original signature:<br>
	 * {@code getDomNode(): HTMLElement; }<br>
	 */
	public JSObject getDomNode() { return call("getDomNode", ofMapped(JSObject.class)); }

 	/**
	 * <p>Get the computed diff information.</p>
	 * See {@code monaco.d.ts:4608:22}<br>
	 * Original signature:<br>
	 * {@code getLineChanges(): ILineChange[] | null; }<br>
	 */
	public Optional<List<ILineChange>> getLineChanges() { return Optional.ofNullable(call("getLineChanges", ofArray(ILineChange::new))); }

 	/**
	 * <p>Type the getModel() of IEditor.</p>
	 * See {@code monaco.d.ts:4587:16}<br>
	 * Original signature:<br>
	 * {@code getModel(): IDiffEditorModel | null; }<br>
	 */
	public Optional<IDiffEditorModel> getModel_() { return Optional.ofNullable(call("getModel", IDiffEditorModel::new)); }

 	/**
	 * <p>Get the <code>modified</code> editor.</p>
	 * See {@code monaco.d.ts:4604:25}<br>
	 * Original signature:<br>
	 * {@code getModifiedEditor(): ICodeEditor; }<br>
	 */
	public ICodeEditor getModifiedEditor() { return call("getModifiedEditor", ICodeEditor::new); }

 	/**
	 * <p>Get the <code>original</code> editor.</p>
	 * See {@code monaco.d.ts:4600:25}<br>
	 * Original signature:<br>
	 * {@code getOriginalEditor(): ICodeEditor; }<br>
	 */
	public ICodeEditor getOriginalEditor() { return call("getOriginalEditor", ICodeEditor::new); }

 	/**
	 * <p>Restores the view state of the editor from a serializable object generated by <code>saveViewState</code>.</p>
	 * See {@code monaco.d.ts:4583:24}<br>
	 * Original signature:<br>
	 * {@code restoreViewState(state: IDiffEditorViewState): void; }<br>
	 */
	public void restoreViewState_(@Nonnull IDiffEditorViewState state) { call("restoreViewState", ofVoid(), state); }

 	/**
	 * <p>Saves current view state of the editor in a serializable object.</p>
	 * See {@code monaco.d.ts:4579:21}<br>
	 * Original signature:<br>
	 * {@code saveViewState(): IDiffEditorViewState | null; }<br>
	 */
	public Optional<IDiffEditorViewState> saveViewState_() { return Optional.ofNullable(call("saveViewState", IDiffEditorViewState::new)); }

 	/**
	 * <p>Sets the current model attached to this editor.
	 * If the previous model was created by the editor via the value key in the options
	 * literal object, it will be destroyed. Otherwise, if the previous model was set
	 * via setModel, or the model key in the options literal object, the previous model
	 * will not be destroyed.
	 * It is safe to call setModel(null) to simply detach the current model from the editor.</p>
	 * See {@code monaco.d.ts:4596:16}<br>
	 * Original signature:<br>
	 * {@code setModel(model: IDiffEditorModel | null): void; }<br>
	 */
	public void setModel_(@Nullable IDiffEditorModel model) { call("setModel", ofVoid(), model); }

 	/**
	 * <p>Update the editor's options after the editor has been created.</p>
	 * See {@code monaco.d.ts:4622:21}<br>
	 * Original signature:<br>
	 * {@code updateOptions(newOptions: IDiffEditorOptions): void; }<br>
	 */
	public void updateOptions_(@Nonnull IDiffEditorOptions newOptions) { call("updateOptions", ofVoid(), newOptions); }

 
}
